### ISSUE TITLE
Flux architecture 

### ISSUE THREAD

**Issue by mikhail-riabokon** [infiman/react-todo#1]
* Create todoStore instance in TodoStore file, so in this case your store will be singleton.
```
class TodoStore {
// define store
}

const todoStore = new TodoStore();

export default todoStore;
```

* You've created App dispatcher  in todo actions, so as App dispatcher should have only one instance per flux application, you should move this from actions.
```
//dispatcher.js
import Dispatcher from 'path/to/dispatcher';

const appDispatcher = new Dispatcher();

export default appDispatcher;

// any.store.js

import appDispatcher from 'dispatcher.js';

// do register your events
```

* You should register your dispatcher actions in store.
```
Flux 
| Action | ----> | Dispatcher | ----> | Store | ----> | View |
```
So in action you dispatch you *Action*,  dispatcher send this actions to all places where you register dispatcher changes (it should be *Stores*), *Store* does some changes by action, and should fired change event, so *View*, which register for store changes, would know about this.

**Comment by infiman** [comment]
Fixed in ff6f034 commit
